### ISSUE TITLE
Errors for watching files

### ISSUE THREAD

**Issue by chrishrb** [aarol/reload#3]
Hello,
some users of my little go application have an issue, which I think is related to your reload library that I use: https://github.com/chrishrb/go-grip/issues/6.
Do you have any idea what could be wrong here? I can‘t reproduce it (i'm on macos).

**Comment by aarol** [comment]
Sure, I'll try to reproduce this

**Comment by aarol** [comment]
I think it's fixed now, couldn't reproduce it straight away but I did notice an obvious bug in the code which was very likely the culprit.
